### ISSUE TITLE
Clear input fields on focus

### ISSUE THREAD

**Issue by bramdevries** [madewithlove/semver#10]
When focusing on the input fields it should clear both the package name and version number field.

**Comment by Anahkiasen** [comment]
Won't that be extremely annoying? Or do you mean only the first time?

**Comment by bramdevries** [comment]
Maybe put the current content: `madewithlove/elasticsearch` and `0.1.*` as placeholders then

**Comment by hannesvdvreken** [comment]
I would just do select all text on focus.
