### ISSUE TITLE
Can't select a package when another package with a more specific name exist

### ISSUE THREAD

**Issue by petitphp** [madewithlove/semver#217]
I've stumble upon this issue several time and I don't know if it's something I'm doing wrong or a real issue.

When I try to test constraints for the package [`roots/wordpress`](https://semver.madewithlove.com/?package=roots%2Fwordpress&constraint=dev-main&stability=stable), I'm shown a list of two possible package for that name `roots/wordpress` and `roots/wordpress-core-installer`.

If I click on `roots/wordpress-core-installer` the website correctly update with the results. But if I try to choose `roots/wordpress` nothing happens (or I should say the website refresh but still want me to "choose" between the two options).

I can't find a way around this behavior.

**Comment by jdrieghe** [comment]
Thanks for the bug report @petitphp. I was able to reproduce this issue and I could trace it back to one of our dependencies.
I pushed a fix for it [here](https://github.com/KnpLabs/packagist-api/pull/78), but it might take some time for the maintainer to publish a new version. As soon as that version is published, I will update the dependency in our tool.

**Comment by petitphp** [comment]
Thanks @jdrieghe !

**Comment by jdrieghe** [comment]
@petitphp there you go https://semver.madewithlove.com/?package=roots%2Fwordpress&constraint=dev-main&stability=stable

**Comment by petitphp** [comment]
Great ! Thanks again @jdrieghe !
