### ISSUE TITLE
Add mwl logo

### ISSUE THREAD

**Issue by hannesvdvreken** [madewithlove/semver#22]
![image](https://cloud.githubusercontent.com/assets/1410358/7319152/855cb4e6-ea93-11e4-9134-85faa889a60d.png)

**Comment by hannesvdvreken** [comment]
@eliedevlieger like this?

![screen shot 2015-04-24 at 15 28 44](https://cloud.githubusercontent.com/assets/1410358/7319540/aa8707dc-ea96-11e4-92e3-be93472c6930.png)

**Comment by eliedevlieger** [comment]
Yes! But a bit lower on the page maybe and all the same boldness in 'madewithlove'

**Comment by hannesvdvreken** [comment]
lower on the page? it's at the very bottom

![screen shot 2015-04-24 at 15 32 57](https://cloud.githubusercontent.com/assets/1410358/7319641/38f7eab8-ea97-11e4-9453-f1520410cd30.png)

**Comment by eliedevlieger** [comment]
Ok nevermind, because of the big screen. Do it live!
