### ISSUE TITLE
Represent what composer would add as constraint to front-end

### ISSUE THREAD

**Issue by hannesvdvreken** [madewithlove/semver#3]
`GET /packages/{vendor}/{package}`

now returns

```js
{
    "default_constraint": "~1.0",
    "versions": [...]
}
```

The default constraint can be filled in the second input field if it is empty.

In future versions of composer this will probably change to something with a caret (`^`)

**Comment by Anahkiasen** [comment]
We could simply use it as placeholder for the version field and also set the version field's value to it when changing package
