### ISSUE TITLE
Beta versions are not compared properly with their stable versions

### ISSUE THREAD

**Issue by stof** [madewithlove/semver#30]
See http://semver.mwl.be/#?package=symfony%2Fsymfony&version=%3C2.7.0&minimum-stability=dev

2.7.0-beta1 should be considered lower than the 2.7.0 release and so be matched here. But your code does not match it

**Comment by tonysm** [comment]
Thanks for the report, we are investigating.

**Comment by tonysm** [comment]
Reproducing the issue:

```
$parser = new VersionParser();
$constraint = $parser->parseConstraints('<2.7.0');
$version = new VersionConstraint('==', $parser->normalize('v2.7.0-BETA1'));

// fails
$this->assertTrue($constraint->matches($version));
```

I'll investigate further later..

\cc @hannesvdvreken

**Comment by hannesvdvreken** [comment]
Closing this as we cannot do anything in this repository to change this.
