### ISSUE TITLE
Test method names

### ISSUE THREAD

**Issue by nbayramberdiyev** [madewithlove/semver#335]
The test method names are displayed weirdly (for example, see [this](https://github.com/madewithlove/semver/blob/main/tests/Unit/Version/MatcherTest.php#L19)). And my IDE displays it like so:
<img width="715" alt="Screen Shot 2022-08-09 at 17 27 50" src="https://user-images.githubusercontent.com/23094428/183675208-36a7ca70-d0b4-41e4-bbae-9b03f70d0a7e.png">
I wonder, is this intentional? If not, I'm happy to work on a PR that replaces them all with an underscore.

**Comment by WouterSioen** [comment]
I like it but it's not like I have such a hard opinion on it. If this doesn't work for other people, I'll definitely accept the changes.

**Comment by nbayramberdiyev** [comment]
Cool! Closing for now. Thanks!
