### ISSUE TITLE
website https issue

### ISSUE THREAD

**Issue by jakoch** [madewithlove/semver#37]
Hi there :)

I'm running into the following problem
`https://semver.mwl.be SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed`

The certificate verification fails, because the Let's Encrypt certificate is expired. 

Best, Jens

**Comment by hannesvdvreken** [comment]
Hi Jens,
Thanks for letting us know. The letsencrypt certificate renewal failed. Renewed it manually.

Cheers!
