### ISSUE TITLE
Version & stability constraints are ignored

### ISSUE THREAD

**Issue by bwaidelich** [madewithlove/semver#38]
With the current version running on the public server, the version & stability constraint selectors are ignored leading to invalid results.

e.g. https://semver.mwl.be/#?package=madewithlove%2Felasticsearcher&version=0.4.1&minimum-stability=dev

should only highlight `0.4.1` but it seems to ignore both parameters and only highlights all stable versions no matter what is selected.

BTW: When debugging the cause I realized that your server outputs debug details (i.e. for 404s) - in case that's not intended...

**Comment by hannesvdvreken** [comment]
You're right. It is definitely off. Was probably introduced here: https://github.com/madewithlove/semver/pull/36

Will take a look at fixing it as soon as I have the time.

**Comment by hannesvdvreken** [comment]
In the mean time, you're very welcome at installing it locally and finding what went wrong, to send us a PR. We'd be happy to merge it.

**Comment by bwaidelich** [comment]
Thanks for the quick feedback.
It seems #36 is the culprit indeed:
```php
$this->request->getAttribute('constraint', '*')
```
in `PackageController::matchVersions()` is always `null`. I'm not too deep into Symfony so I don't know whether `ServerRequest::attributes` is meant to be populated by the router, but using `$this->request->getQueryParams()` seems to work.

**Comment by hannesvdvreken** [comment]
@bwaidelich A PR to fix those 2 lines would be appreciated!

**Comment by bwaidelich** [comment]
There yo go

**Comment by hannesvdvreken** [comment]
Thanks again @bwaidelich! It's fixed now, so it seams: https://semver.mwl.be/#?package=madewithlove%2Felasticsearcher&version=0.4.1&minimum-stability=dev Thanks to your input.

**Comment by bwaidelich** [comment]
Cheers!
