### ISSUE TITLE
Support alternate repositories

### ISSUE THREAD

**Issue by FGM** [madewithlove/semver#40]
I like this service a lot, but currently it seems to only rely on Packagist proper, but I often need similar services from https://packages.drupal.org/8/packages.json : (equivalent version exists with /7) It would be nice if the site would default to Packagist, but also support a set of well-known directories like this one. Adding free entry for the directory URL woud probably for more security-vetting, but it seems just adding a list of a few alternate repos should not be a problem.

**Comment by hannesvdvreken** [comment]
Hi, Frédéric,

I've taken a few days to think about this.

We're not really eager to work on this feature. It's called the "packagist" semver checker after all. But you are very free to clone this project, and add that feature yourself. We have only one request: when you host an altered version of this project, at least keep a reference to our original version on each page view.

Cheers!
