### ISSUE TITLE
stability-flags override "Minimum Stability" for package

### ISSUE THREAD

**Issue by lucascampelo** [madewithlove/semver#41]
I'm trying to use `version` with `stability-flags`, but it does not seem to be matching. For example: https://semver.mwl.be/#?package=monolog%2Fmonolog&version=1.0.*@dev&minimum-stability=stable.

Maybe the `stability-flags` override the `Minimum Stability` or auto-change dropdown (after read the docs below, i think its more Composer-like the override method).

Testing with composer, the match is different. Please check composer documentation bellow:
https://getcomposer.org/doc/articles/versions.md#stability
https://getcomposer.org/doc/04-schema.md#package-links

I would like to thank you for this tool, its really useful.

**Comment by hannesvdvreken** [comment]
So... What you're saying is: if the version input has a `@<stability>` it should set the dropdown automatically?

**Comment by hannesvdvreken** [comment]
Or should it override the input from the dropdown?

**Comment by lucascampelo** [comment]
Override the input from dropdown, without change it. The `Minimum Stability` config its for the main project. However, the `stability-flags` its for the dependency.

**Comment by hannesvdvreken** [comment]
Well... to be honest, there's no "project" here, only "dependency" so it's a single constraint.

We currently ignore the `@<stability>` so just set it using the dropdown:

https://semver.mwl.be/#?package=monolog%2Fmonolog&version=1.0.*&minimum-stability=dev

**Comment by hannesvdvreken** [comment]
We're closing this issue because we don't think action/change is required.

**Comment by lucascampelo** [comment]
The command (`composer require however`) generated still wrong anyway

**Comment by hannesvdvreken** [comment]
@lucascampelo right! Will put it on my to-do list!
