### ISSUE TITLE
Testing tilde `~` semver range returns unexpected resuts

### ISSUE THREAD

**Issue by ntwb** [madewithlove/semver#43]
Testing `phpunit/phpunit` and `~4.2` includes 4.3, 4.4, 4.5, 4.6, 4.7, and 4.8 as valid versions

It shouldn't, I expect those values to only be returned when using the caret version `^4.2`

• Tilde `~4.2` -> [https://semver.mwl.be/#?package=phpunit%2Fphpunit&version=~4.2](https://semver.mwl.be/#?package=phpunit%2Fphpunit&version=~4.2&minimum-stability=stable)
• Caret `^4.2` -> [https://semver.mwl.be/#?package=phpunit%2Fphpunit&version=^4.2](https://semver.mwl.be/#?package=phpunit%2Fphpunit&version=%5E4.2&minimum-stability=stable)

**Comment by hannesvdvreken** [comment]
I'm sorry, but those are actually correct.

More information here:
- https://blog.madewithlove.be/post/tilde-and-caret-constraints/ 
- https://getcomposer.org/doc/articles/versions.md#next-significant-release-operators

**Comment by ntwb** [comment]
Thanks, today I learned Composer and npm have different interpretations and implementations of semantic versioning 😖 

 Tilde `~` minor version
• npm & composer: `"vendor/package": "~1.3.2",` // >=1.3.2 <1.4.0
• npm only: `"vendor/package": "~1.3",` // >=1.3.0 <1.4.0
• composer only: `"vendor/package": "~1.3",` // >=1.3.0 <2.0.0

 Caret `^` major version
• npm & composer: `"vendor/package": "^1.3.2",` // >=1.3.2 <2.0.0
• npm & composer: `"vendor/package": "^1.3",` , // >=1.3.2 <2.0.0

**Comment by hannesvdvreken** [comment]
Exactly 👍  no worries.
