### ISSUE TITLE
Not able to fetch versions of psalm/phar

### ISSUE THREAD

**Issue by alfredbez** [madewithlove/semver#57]
Hello there, thanks for this neat tool!

I found some weird behavior today: You're not able to fetch the versions for `psalm/phar` here: https://semver.mwl.be/#!?package=psalm%2Fphar&version=%5E3.12&minimum-stability=stable

The error actually is caused by this: https://semver.mwl.be/packages/psalm/phar

![image](https://user-images.githubusercontent.com/1001186/96719071-397fa700-13a9-11eb-8705-c4d0152fdee4.png)

**Comment by WouterSioen** [comment]
This has been fixed now!

**Comment by WouterSioen** [comment]
Ah, nevermind, there's still a bug here!

**Comment by WouterSioen** [comment]
Okay, this really is fixed now 😓
