### ISSUE TITLE
Start using Changehub

### ISSUE THREAD

**Issue by bramdevries** [madewithlove/semver#9]
Tag a 1.0.0 release and add a link to the public Changehub page

**Comment by hannesvdvreken** [comment]
:stuck_out_tongue:

**Comment by Anahkiasen** [comment]
Tagged a 1.0 on 203ea27bd17259d8fa301e451d741046505fdd19 which is more or less up to where the "first draft" of the app is, rest is in PRs so we can have a nice changelog for next version

**Comment by hannesvdvreken** [comment]
Is it worth to have a `develop` branch? If not, every PR merge is a new release.

**Comment by Anahkiasen** [comment]
Yeah we should probably have a develop branch

**Comment by hannesvdvreken** [comment]
Done
